config/routes.rb
Wdim::Application.routes.draw do

  resources :users do
    resources :avatars, only: [:index, :new, :create, :update]
    resources :messages, only: [:new, :create, :update]
  end

  resources :avatars, only: [:show, :edit, :destroy]
  resources :messages, only: [:index, :show, :edit, :destroy]

  resources :banners
  resources :sessions

  get       "login"   => "sessions#new", as: "log_in"
  get       "logout"   => "sessions#destroy", as: "log_out"
  root      to: "sessions#new"
end

app/models/message.rb
class Message < ActiveRecord::Base

  has_ancestry

  belongs_to            :user

  validates             :user_id, :body,
                          presence: true

  validates             :title,
                          presence: true,
                          if: "self.is_root? == true"

  before_save           :update_caches

  attr_accessible       :body, :date, :last_post_date, :last_post_id, :old_id, :reply_count, :title, :user_id

  def update_caches
    self.date = Time.now
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter   :get_resources

  def index
    if @user
      @messages = @user.messages.all
    else
      @messages = Message.all
    end


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  def new
    @message = @user.messages.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  def edit
  end

  def create
    @message = @user.messages.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    respond_to do |format|
      if @message.update_attributes(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end

  private

    def get_resources
      @user ||= User.find(params[:user_id]) if params[:user_id]

      if @user
        @message = @user.messages.find(params[:id]) if params[:id]
      else
        @message = Message.find(params[:id]) if params[:id]
        @user = @message.user if @message
      end
    end

    def message_params
      params.require(:message).permit(:body, :date, :last_post_date, :last_post_id, :old_id, :reply_count, :title, :user_id)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.haml
= form_for [@user, @message] do |f|
  - if @message.errors.any?
    #error_explanation
      %h2= "#{pluralize(@message.errors.count, "error")} prohibited this message from being saved:"
      %ul
        - @message.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title, autofocus: true
  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit 'Save'

app/views/messages/edit.html.haml
%h1 Editing message

= render 'form'

= link_to 'Show', @message
\|
= link_to 'Back', messages_path

app/views/messages/index.html.haml
%h1 Listing messages

%table
  %tr
    %th Title
    %th User
    %th Reply count
    %th Last post date
    %th

  - @messages.each do |message|
    - present message do |message_presenter|
      %tr
        %td= link_to message.title, message
        %td= link_to message.user.username, user_path(message.user)
        %td= message.reply_count
        %td= message.date
        %td
          = message_presenter.edit_link
          = message_presenter.destroy_link

%br

= link_to 'New Message', new_user_message_path(current_user)

app/views/messages/new.html.haml
%h1 New message

= render 'form'

= link_to 'Back', messages_path

app/views/messages/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @message.title
%p
  %b Body:
  = @message.body
%p
  %b Date:
  = @message.date
%p
  %b User:
  = @message.user_id
%p
  %b Last post date:
  = @message.last_post_date
%p
  %b Last post:
  = @message.last_post_id
%p
  %b Reply count:
  = @message.reply_count

= link_to 'Edit', edit_message_path(@message)
\|
= link_to 'Back', messages_path