config/routes.rb
Wdim::Application.routes.draw do

  resources :users do
    resources :avatars, only: [:index, :new, :create, :update]
    resources :messages, only: [:new, :create, :update]
  end

  resources :avatars, only: [:show, :edit, :destroy]
  resources :messages, only: [:index, :show, :edit, :destroy]

  resources :banners
  resources :sessions

  get       "login"   => "sessions#new", as: "log_in"
  get       "logout"   => "sessions#destroy", as: "log_out"
  root      to: "sessions#new"
end

app/models/banner.rb
class Banner < ActiveRecord::Base
  has_attached_file     :image,
                          path: ':rails_root/public/stage/banners/:banner.:extension',
                          url: '/stage/banners/:banner.:extension',
                          whiny: false,
                          styles: {
                            :default => "780x100>"
                          }

  validates             :title,
                          presence: true,
                          length: { minimum: 2 }

  validates_attachment  :image,
                          presence: true

  attr_accessible       :old_id, :title, :image
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController

  def index
    @banners = Banner.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @banners }
    end
  end

  def show
    @banner = Banner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @banner }
    end
  end

  def new
    @banner = Banner.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @banner }
    end
  end

  def edit
    @banner = Banner.find(params[:id])
  end

  def create
    @banner = Banner.new(banner_params)

    respond_to do |format|
      if @banner.save
        format.html { redirect_to @banner, notice: 'Banner was successfully created.' }
        format.json { render json: @banner, status: :created, location: @banner }
      else
        format.html { render action: "new" }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @banner = Banner.find(params[:id])

    respond_to do |format|
      if @banner.update_attributes(banner_params)
        format.html { redirect_to @banner, notice: 'Banner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @banner = Banner.find(params[:id])
    @banner.destroy

    respond_to do |format|
      format.html { redirect_to banners_url }
      format.json { head :no_content }
    end
  end

  private

    def banner_params
      params.require(:banner).permit(:old_id, :title, :image)
    end
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/views/banners/_form.html.haml
= form_for @banner, html: { :multipart => true } do |f|
  - if @banner.errors.any?
    #error_explanation
      %h2= "#{pluralize(@banner.errors.count, "error")} prohibited this banner from being saved:"
      %ul
        - @banner.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title, autofocus: true
  .field
    = f.label :image
    = f.file_field :image
  / .field
  /   = f.label :old_id
  /   = f.number_field :old_id
  .actions
    = f.submit 'Save'

app/views/banners/edit.html.haml
%h1 Editing Banner

= render 'form'

= link_to 'Show', @banner
\|
= link_to 'Back', banners_path

app/views/banners/index.html.haml
%h1 Listing Banners

%table
  %tr
    %th Title
    %th Thumbnail
    %th Options

  - @banners.each do |banner|
    %tr
      %td= banner.title
      %td= image_tag(banner.image.url(:thumb))
      %td
        = link_to 'Show', banner
        = link_to 'Edit', edit_banner_path(banner)
        = link_to 'Destroy', banner, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Banner', new_banner_path

app/views/banners/new.html.haml
%h1 New Banner

= render 'form'

= link_to 'Back', banners_path

app/views/banners/show.html.haml
%h1 Banner Details
%p#notice= notice

%p
  %b Title:
  = @banner.title
%p
  %b Image:
  = link_to image_tag(@banner.image.url(:thumb)), @banner.image.url
/ %p
/   %b Old:
/   = @banner.old_id

= link_to 'Edit', edit_banner_path(@banner)
\|
= link_to 'Back', banners_path