config/routes.rb
Wdim::Application.routes.draw do

  resources :users do
    resources :avatars, only: [:index, :new, :create, :update]
    resources :messages, only: [:new, :create, :update]
  end

  resources :avatars, only: [:show, :edit, :destroy]
  resources :messages, only: [:index, :show, :edit, :destroy]

  resources :banners
  resources :sessions

  get       "login"   => "sessions#new", as: "log_in"
  get       "logout"   => "sessions#destroy", as: "log_out"
  root      to: "sessions#new"
end

app/models/user.rb
class User < ActiveRecord::Base
  USER_TYPES =        ["admin", "default"].freeze

  has_secure_password

  has_many            :avatars,
                        dependent: :destroy
  has_many            :messages

  validates           :username,
                        presence: true,
                        uniqueness: { case_sensitive: false },
                        length: { minimum: 2, maximum: 45 }

  validates           :password,
                        presence: true,
                        length: { minimum: 5, maximum: 25 },
                        on: :create

  validates           :first_name,
                        presence: true,
                        length: { minimum: 2, maximum: 45 }

  validates           :last_name,
                        presence: true,
                        length: { minimum: 2, maximum: 45 }

  validates           :email,
                        presence: true,
                        format: { with: /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }

  validates           :user_type,
                        presence: true,
                        inclusion: { in: User::USER_TYPES }

  attr_accessible     :active, :aim, :at_work, :email, :first_name, :last_name, :member_since, :old_id, :password_digest, :posts_count, :user_type, :username, :password, :password_confirmation

  before_validation   :set_defaults,
                        on: :create

  def set_defaults
    if self.user_type.nil?
      self.user_type = "default"
    end

    if self.member_since.nil?
      self.member_since = Date.current
    end
  end

  def is_admin?
    self.user_type == "admin"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private

    def user_params
      params.require(:user).permit(:active, :aim, :at_work, :avatars, :email, :first_name, :last_name, :member_since, :messages, :old_id, :password_digest, :posts_count, :user_type, :username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  / .field
  /   = f.label :user_type
  /   = f.text_field :user_type
  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :aim
    = f.text_field :aim
  / .field
  /   = f.label :member_since
  /   = f.date_select :member_since
  / .field
  /   = f.label :posts_count
  /   = f.number_field :posts_count
  .field
    = f.label :at_work
    = f.check_box :at_work
  / .field
  /   = f.label :active
  /   = f.check_box :active
  / .field
  /   = f.label :messages
  /   = f.text_field :messages
  / .field
  /   = f.label :avatars
  /   = f.text_field :avatars
  / .field
  /   = f.label :old_id
  /   = f.number_field :old_id
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing User

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing Users

%table
  %tr
    %th Username
    %th First name
    %th Last name
    %th Email
    %th User type
    %th Member since
    %th Posts count
    %th At work
    %th Active
    %th Options

  - @users.each do |user|
    %tr
      %td= user.username
      %td= user.first_name
      %td= user.last_name
      %td= user.email
      %td= user.user_type
      %td= user.member_since
      %td= user.posts_count
      %td= user.at_work
      %td= user.active
      %td
        = link_to 'Avatars', user_avatars_path(user)
        = link_to 'Show', user
        = link_to 'Edit', edit_user_path(user)
        = link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New User

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%h1 User Details
%p#notice= notice

%p
  %b Username:
  = @user.username
/ %p
/   %b Password digest:
/   = @user.password_digest
%p
  %b User type:
  = @user.user_type
%p
  %b First name:
  = @user.first_name
%p
  %b Last name:
  = @user.last_name
%p
  %b Email:
  = @user.email
%p
  %b Aim:
  = @user.aim
%p
  %b Member since:
  = @user.member_since
%p
  %b Posts count:
  = @user.posts_count
%p
  %b At work:
  = @user.at_work
/ %p
/   %b Active:
/   = @user.active
/ %p
/   %b Messages:
/   = @user.messages
/ %p
/   %b Avatars:
/   = @user.avatars
/ %p
/   %b Old:
/   = @user.old_id

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path