config/routes.rb
Wdim::Application.routes.draw do

  resources :users do
    resources :avatars, only: [:index, :new, :create, :update]
    resources :messages, only: [:new, :create, :update]
  end

  resources :avatars, only: [:show, :edit, :destroy]
  resources :messages, only: [:index, :show, :edit, :destroy]

  resources :banners
  resources :sessions

  get       "login"   => "sessions#new", as: "log_in"
  get       "logout"   => "sessions#destroy", as: "log_out"
  root      to: "sessions#new"
end

app/models/avatar.rb
class Avatar < ActiveRecord::Base
  has_attached_file     :image,
                          path: ':rails_root/public/stage/:user/:basename_:style.:extension',
                          url: '/stage/:user/:basename_:style.:extension',
                          whiny: false,
                          styles: {
                            :thumb => "150x150>"
                          }

  belongs_to            :user

  validates             :name,
                          presence: true

  validates             :title,
                          presence: true

  validates_attachment  :image,
                          presence: true,
                          content_type: { content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif', 'image/png'] },
                          size: { in: 0..1.megabytes }

  attr_accessible       :active, :location, :name, :signature, :title, :user_id, :image

  after_save            :check_active

  def check_active
    if self.active_changed? && self.active == true
      user = self.user
      avatars = user.avatars.where('id != ? AND active == ?', self.id, true)
      avatars.update_all(active: false)
    end
  end
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  before_filter   :get_resources

  def index
    @avatars = @user.avatars.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @avatars }
    end
  end

  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @avatar }
    end
  end

  def new
    @avatar = @user.avatars.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @avatar }
    end
  end

  def edit
  end

  def create
    @avatar = @user.avatars.new(avatar_params)

    respond_to do |format|
      if @avatar.save
        format.html { redirect_to user_avatars_path(@user), notice: 'Avatar was successfully created.' }
        format.json { render json: @avatar, status: :created, location: @avatar }
      else
        format.html { render action: "new" }
        format.json { render json: @avatar.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    respond_to do |format|
      if @avatar.update_attributes(avatar_params)
        format.html { redirect_to user_avatars_path(@user), notice: 'Avatar was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @avatar.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @avatar.destroy

    respond_to do |format|
      format.html { redirect_to user_avatars_path(@user) }
      format.json { head :no_content }
    end
  end

  private

    def get_resources
      @user ||= User.find(params[:user_id]) if params[:user_id]

      if @user
        @avatar = @user.avatars.find(params[:id]) if params[:id]
      else
        @avatar = Avatar.find(params[:id]) if params[:id]
        @user = @avatar.user
      end
    end

    def avatar_params
      params.require(:avatar).permit(:active, :location, :name, :signature, :title, :user_id, :image)
    end
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/views/avatars/_form.html.haml
= form_for [@user, @avatar], html: { multipart: true } do |f|
  - if @avatar.errors.any?
    #error_explanation
      %h2= "#{pluralize(@avatar.errors.count, "error")} prohibited this avatar from being saved:"
      %ul
        - @avatar.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name, autofocus: true
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :location
    = f.text_field :location
  .field
    = f.label :signature
    = f.text_area :signature
  .field
    = f.label :active
    = f.check_box :active
  .field
    = f.label :image
    = f.file_field :image
  / .field
  /   = f.label :user_id
  /   = f.number_field :user_id
  .actions
    = f.submit 'Save'

app/views/avatars/edit.html.haml
%h1 Editing Avatar

= render 'form'

= link_to 'Show', avatar_path(@avatar)
\|
= link_to 'Back', user_avatars_path(@user)

app/views/avatars/index.html.haml
%h1
  Listing Avatars for
  = link_to @user.username, @user

%table
  %tr
    %th Name
    %th Title
    %th Location
    %th Signature
    %th Active
    %th Thumbnail
    %th Options

  - @avatars.each do |avatar|
    %tr
      %td= avatar.name
      %td= avatar.title
      %td= avatar.location
      %td= avatar.signature
      %td= avatar.active
      %td= image_tag avatar.image.url(:thumb)
      %td
        = link_to 'Show', avatar
        = link_to 'Edit', edit_avatar_path(avatar)
        = link_to 'Destroy', avatar, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Avatar', new_user_avatar_path(@user)

app/views/avatars/new.html.haml
%h1
  New Avatarfor
  = link_to @user.username, @user

= render 'form'

= link_to 'Back', user_avatars_path(@user)

app/views/avatars/show.html.haml
%h1 Avatar Details

%p#notice= notice

%p
  %b Name:
  = @avatar.name
%p
  %b Title:
  = @avatar.title
%p
  %b Location:
  = @avatar.location
%p
  %b Signature:
  = @avatar.signature
%p
  %b Active:
  = @avatar.active
%p
  %b Image:
  = link_to (image_tag @avatar.image.url(:default)), @avatar.image.url, target: "_blank"

= link_to 'Edit', edit_avatar_path(@avatar)
\|
= link_to 'Back', user_avatars_path(@user)